config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :entries

  resources :blogs

  devise_for :users
  get 'pages/home'

  root 'pages#home'

end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Blog < ActiveRecord::Base
  belongs_to :user
  has_many :entries
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  text       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to :entry
  has_one :user
end

app/models/entry.rb
# == Schema Information
#
# Table name: entries
#
#  id         :integer          not null, primary key
#  title      :string
#  text       :text
#  image      :string
#  video      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Entry < ActiveRecord::Base
  belongs_to :blog
  has_many :comments
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  has_many :blogs
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, password_length: 5..20
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
    @blogs = Blog.paginate(page: params[:page], per_page:10)
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :description)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
    @comments = Comment.paginate(page: params[:page], per_page:8)
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :text)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
    @entries = Entry.paginate(page: params[:page], per_page:3)
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :text, :image, :video)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="forms">

<h1>Editing Blog</h1>

<%= render 'form' %>

<div class="other-links">
  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</div>

</div>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<div class="row container-fluid">
  <% @blogs.each do |blog| %>
    <div id="blogs" class="col-md-4 container-fluid">
      <a class="btn btn-default blog-page" href="/entries" role="button">
        <h2><%= blog.title %></h2>
        <p><%= blog.description %></p>
      </a>
        <p>
          <a href="/entries">Show</a>
          <%= link_to 'Edit', edit_blog_path(blog) %>
          <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
    </div>
  <% end %>
</div>

<br>

<%= will_paginate @blogs %>

<div class="new">
<%= link_to 'New Blog', new_blog_path %>
</div>

app/views/blogs/new.html.erb
<div class="forms">

  <h1>New Blog</h1>

  <%= render 'form' %>

<div class="other-links">
  <%= link_to 'Back', blogs_path %>
</div>

</div>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row container-fluid entries">
  <div class="entry container">
    <h1><%= @blog.title %></h1>
    <p><%= @blog.description %></p>
  </div>
</div>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="forms">

<h1>Editing Comment</h1>

<%= render 'form' %>

<div class="other-links">
  <%= link_to 'Show', @comment %> |
  <%= link_to 'Back', comments_path %>
</div>

</div>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.text %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to 'New Comment', new_comment_path %></p>
<p><%= will_paginate @comments %></p>

app/views/comments/new.html.erb
<div class="forms">

<h1>New Comment</h1>

<%= render 'form' %>

<div class="other-links">
  <%= link_to 'Back', comments_path %>
</div>
</div>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :video %><br>
    <%= f.text_field :video %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="forms">

<h1>Editing Entry</h1>

<%= render 'form' %>

<div class="other-links">
  <%= link_to 'Show', @entry %> |
  <%= link_to 'Back', entries_path %>
</div>

</div>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <h1>Entries</h1>

  <div class="container-fluid row layout">

    <div class="col-md-8 container-fluid entries">
      <% @entries.each do |entry| %>
        <div class="entry container-fluid">
          <h2><%= entry.title %></h2>
          <p><%= entry.text %></p>
          <img src="<%= entry.image %>"></img>
          <img src="<%= entry.video %>"></img>
        </div>
          <p>
            <%= link_to 'Show', entry %> |
            <%= link_to 'Edit', edit_entry_path(entry) %> |
            <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %> |
            <a href="comments/new/">Comment</a>
          </p>
      <% end %>
    </div>

    <div class="col-md-4">
      <div class="search">
        <form class="navbar-form" role="search">
          <div class="form-group in-line">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="submit btn btn-default">Submit</button>
        </form>
      </div>
      <div class="new">
        <button type="button" id="sm-btn" class="btn btn-default btn-lg navbar-left">
          <p><i class="fa fa-plus"> <%= link_to 'New Entry', new_entry_path %></i></p>
        </button>
      </div>
    </div>

  </div>
</div>
<br>

<p><%= link_to 'New Entry', new_entry_path %></p>
<p><%= will_paginate @entries %></p>

app/views/entries/new.html.erb
<div class="forms">

<h1>New Entry</h1>

<%= render 'form' %>

  <div class="other-links">
    <%= link_to 'Back', entries_path %>
  </div>

</div>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row container-fluid entries">
  <div class="entry container">
    <h2><%= @entry.title %></h2>
    <p><%= @entry.text %></p>
    <img src="<%= @entry.image %>"></img>
    <img src="<%= @entry.video %>"></img>
  </div>
</div>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,700,400|Gentium+Book+Basic:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <nav class="navbar navbar-transparent">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">BLOGGER</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li><a href="/blogs">Blogs</a></li>
        <li><a href="/entries">Entries</a></li>
        <li><a href="/comments">Comments</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="no-bullet">
          <%= render 'devise/menu/registration_items' %>
          <%= render 'devise/menu/login_items' %>
        </li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>


<footer class="navbar-fixed-bottom footer">
  <div class="container-fluid">
      <div id="year" class="col-sm-6">
        <p>&copy; <%= Time.now.year %></p>
      </div>
      <div id="code" class="col-sm-6">
        <a href="https://github.com/katiepatch/blog_app" target="_blank">
          <%= fa_icon "github", text: "Code" %>
        </a>
      </div>
  </div>
</footer>

</body>
</html>

app/views/pages/home.html.erb
<div id="home" class="container">

  <h1 id="greeting">Welcome!</h1>

  <% if user_signed_in? %>

    <div class="col-md-4">
      <button type="button" id="main-btn" class="btn btn-default btn-lg">
        <a href="/blogs"><i class="fa fa-arrow-right"> My Blogs</i></a>
      </button>
    </div>
    <div class="col-md-4">
      <button type="button" id="main-btn" class="btn btn-default btn-lg">
        <a href="/blogs/new"><i class="fa fa-plus"> New Blog</i></a>
      </button>
    </div>
    <div class="col-md-4">
      <button type="button" id="main-btn"class="btn btn-default btn-lg">
        <a href="/blogs"><i class="fa fa-eye"> Explore</i></a>
      </button>
    </div>
  <% else %>
    <button type="button" id="main-btn" class="btn btn-default btn-lg">
      <%= render 'devise/menu/login_items' %>
    </button>
    <button type="button" id="main-btn" class="btn btn-default btn-lg">
      <a href="/blogs"><i class="fa fa-eye"> Explore</i></a>
    </button>
  <% end %>

</div>